version: '3.5'

services:
  elasticsearch: 
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    environment: 
      discovery.type: single-node
    networks:
      - elastic
    ports:
      - 9200:9200
      - 9300:9300
    
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    #environment:
    #  ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elastic
    ports:
      - 5601:5601
    # volumes:
    #   - ./kibana.yml:/usr/share/kibana/config/kibana.yml
  
networks:
  elastic: